# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # Currently available options are "default", "air"
title                    : "Xinglong Wang"
title_separator          : "-"
name                     : &name "Xinglong Wang"
description              : &description "Academic portfolio of Xinglong Wang, focusing on hepatobiliary and pancreatic surgery research"   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : https://wxl9963.github.io # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "wxl9963/wxl9963.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "ZP_wxl.png"
  name             : "Xinglong Wang"
  pronouns         : # example: "he/him"  
  bio              : "MD Candidate in General Surgery, Peking University First Hospital. Research focus: Clinical and basic studies on hepatobiliary and pancreatic diseases, with emphasis on minimally invasive surgery."
  location         : "Beijing, China"
  employer         : "Peking University First Hospital"
  uri              : https://wxl9963.github.io
  email            : "wxl_9963@163.com"

  # Academic websites
  academia         : # URL
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  inspire-hep      : # URL
  impactstory      : # URL
  orcid            : "https://orcid.org/0009-0005-5523-9873"
  semantic         : # URL
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : # URL
  scopus           : # URL


